name: Build and Upload Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install Tauri Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install Dependencies
        run: bun install

      - name: Build Packages
        run: bun run build:packages

      - name: Build Apps
        run: bun run build:apps

      # Upload server artifacts
      - name: Upload Server Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: apps/server/dist/
          if-no-files-found: error
          retention-days: 7

      # Upload web artifacts
      - name: Upload Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/dist/
          if-no-files-found: error
          retention-days: 7

      # Build Tauri app
      - name: Build Tauri
        working-directory: apps/web
        run: bun run build:desktop

      # Upload Tauri artifacts
      - name: Upload Tauri Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: |
            apps/web/src-tauri/target/release/bundle/deb/*
            apps/web/src-tauri/target/release/bundle/appimage/*
            apps/web/src-tauri/target/release/audioling
          if-no-files-found: error
          retention-days: 7
