name: Build Audioling

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: npm install -g bun

      - name: Install Rust and Tauri Dependencies
        shell: powershell
        run: |
          # Download Rust installer safely and execute it
          Invoke-WebRequest -Uri "https://win.rustup.rs" -OutFile "rustup-init.exe"
          Start-Process -Wait -NoNewWindow -FilePath ".\rustup-init.exe" -ArgumentList "-y"
          Remove-Item -Force .\rustup-init.exe
          
          # Update Rust and add required targets
          refreshenv
          rustup update
          rustup default stable
          rustup target add x86_64-pc-windows-msvc
          
          # Install Tauri CLI
          cargo install tauri-cli
          
          # Install Windows build dependencies
          choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools

      - name: Install Project Dependencies
        run: bun install

      - name: Build Packages
        run: bun run build:packages
