name: Build and Upload Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Packages
        run: bun run build:packages

      - name: Build Apps
        run: bun run build:apps

      # Upload server artifacts
      - name: Upload Server Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: apps/server/dist
          retention-days: 7

      # Upload web artifacts
      - name: Upload Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/dist
          retention-days: 7
