name: Build and Upload Audioling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          iwr -useb https://bun.sh/install | iex

      - name: Install Rust and Tauri dependencies
        run: |
          iwr -useb https://win.rustup.rs | iex
          rustup install stable
          rustup default stable
          cargo install tauri-cli

      - name: Clone the audioling repo
        run: git clone https://github.com/ac1mx/audioling.git

      - name: Install dependencies
        working-directory: audioling
        run: bun install

      - name: Build packages
        working-directory: audioling
        run: bun run build:packages

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audioling-artifacts
          path: |
            audioling/apps/web/dist/
            audioling/apps/server/dist/
            audioling/src-tauri/target/release/
